### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/pyfa-ng#1]
Rough thoughts on the design. Follow fairly similar to Pyfa's current design.

**Comment by Ebag333** [comment]
See https://github.com/pyfa-org/pyfa-ng/projects/1 for a rough layout of the new design.

**Comment by Ebag333** [comment]
And a better mockup.

We might land on something similar for tablets.
https://puu.sh/rtdsT/e3d6be3203.gif

For desktops, the left and center columns are okay, but the right column needs to expose more data.

Code block:
main.py

```
#:kivy 1.0

<main>:
    label_wid: my_custom_label
    height: 5000


# Column 1
    BoxLayout:
        BoxLayout:
            size_hint: .3, 1
            orientation: 'vertical'
            padding: 20

            Accordion:
                orientation: 'vertical'

                AccordionItem:
                    title: 'Market'
                    collapse: False

                    Label:
                        text: 'Show market here'

                AccordionItem:
                    title: 'Ships'

                    Label:
                        text: 'Show ship market here'

# Column 2

        BoxLayout:
            size_hint: .4, 1
            orientation: 'vertical'
            padding: 20

            BoxLayout:
                size_hint: 1, .5
                orientation: 'horizontal'
                padding: 0

                Label:
                    id: my_custom_label
                    text: 'Ship Fitting Window'

            BoxLayout:
                size_hint: 1, .5
                orientation: 'horizontal'
                padding: 0

                Accordion:
                    orientation: 'vertical'
                    minspace: '24'
                    min_space: '24'

                    AccordionItem:
                        title: 'Drones\Fighters'
                        collapse: False

                        Label:
                            text: 'Show things like:\nDrones\nFighters'

                    AccordionItem:
                        title: 'Cargo'

                        Label:
                            text: 'Cargo'

                    AccordionItem:
                        title: 'Character\Implants'

                        Label:
                            text: 'Unified window for selecting\ncharacter and implants'

                    AccordionItem:
                        title: 'Projected Effects'

                        Label:
                            text: 'See current panel'


# Start column 3

        BoxLayout:
            size_hint: .3, 1
            orientation: 'vertical'
            padding: 20

            Accordion:
                orientation: 'vertical'

                AccordionItem:
                    title: 'Quick Stats'
                    collapse: False

                    Label:
                        text: 'Show things like:\nCPU\nPG\nEHP\nTotal DPS\nCap Stability'

                AccordionItem:
                    title: 'Detailed Fitting Stats'

                    Label:
                        text: 'CPU\nPG\nCalibration'

                AccordionItem:
                    title: 'Resistances'

                    Label:
                        text: 'See current resistances pane'

                AccordionItem:
                    title: 'Active\Passive Tanking'

                    Label:
                        text: 'See current panel'

                AccordionItem:
                    title: 'DPS'

                    Label:
                        text: 'Weapon DPS\nDrone DPS\nTotal DPS'

                AccordionItem:
                    title: 'Mining Stats'

                    Label:
                        text: 'Laser Yield\nDrone Yield\nTotal Yield\nCycle Time\nRange'

                AccordionItem:
                    title: 'Capacitor'

                    Label:
                        text: 'See current stat pane'

                AccordionItem:
                    title: 'Price'

                    Label:
                        text: 'Ship price\nModule Price\nTotal Price\nInsurance Payouts'

                AccordionItem:
                    title: 'Drones\Fighters'

                    Label:
                        text: 'Drone\Fighter Bay\nActive Drones\Tubes\nDrone Bandwidth\nDrone Control Range'

```

main.py

```
import kivy
kivy.require('1.0.5')

from kivy.uix.boxlayout import BoxLayout
from kivy.app import App
from kivy.properties import ObjectProperty, StringProperty


class main(BoxLayout):
    '''Create a controller that receives a custom widget from the kv lang file.

    Add an action to be called from the kv lang file.
    '''
    label_wid = ObjectProperty()
    info = StringProperty()

    def do_action(self):
        self.label_wid.text = 'My label after button press'
        self.info = 'New info text'


class MainApp(App):

    def build(self):
        return main(info='Hello world')

if __name__ == '__main__':
    MainApp().run()
```
